apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: apitechchallenge  
spec:  
  replicas: 3  
  selector:  
    matchLabels:  
      app: apitechchallenge  
  template:  
    metadata:  
      labels:  
        app: apitechchallenge  
    spec:  
      containers:  
      - name: apitechchallenge  
        image: rianholanda91/apiproducertechchallenge:latest