apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: consumer-techchallenge-regioes  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: consumer-techchallenge-regioes  
  template:  
    metadata:  
      labels:  
        app: consumer-techchallenge-regioes  
    spec:  
      containers:  
      - name: api-producer-techchallenge  
        image: rianholanda91/consumidorregioestechchallenge:latest  