apiVersion: v1  
kind: Service  
metadata:  
  name: apitechchallenge-service  
spec:  
  selector:  
    app: apitechchallenge  
  ports:  
    - protocol: TCP  
      port: 80  
      targetPort: 80  
  type: LoadBalancer 