apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "1q2w3e4r@#"
        volumeMounts:
        - mountPath: /var/opt/mssql
          name: sqlserverdata
      volumes:
      - name: sqlserverdata
        emptyDir: {}
---  
kind: Service
apiVersion: v1
metadata:
  name: sqlserver
spec:
  type: NodePort
  selector:
    app: sqlserver
  ports:
    - port: 1433
      targetPort: 1433
      nodePort: 30003       