name: Docker Compose Actions  
  
on:  
  push:  
    branches:  
      - master  
  
jobs:  
  deploy:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Login to DockerHub  
        uses: docker/login-action@v1  
        with:  
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
  
      - name: Docker compose build  
        run: docker-compose -f docker-compose.yml build  
  
      - name: Docker compose push  
        run: docker-compose -f docker-compose.yml push
